/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.automationmessages;

/**
  Implements a message that is sent in containing a screen shot run during performance test.
**/
@:umodule("AutomationMessages")
@:glueCppIncludes("Public/AutomationWorkerMessages.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FAutomationWorkerScreenImage {
  @:uproperty public var Metadata : unreal.automationmessages.FAutomationScreenshotMetadata;
  
  /**
    The screen shot name.
  **/
  @:uproperty public var ScreenShotName : unreal.FString;
  
  /**
    The screen shot data.
  **/
  @:uproperty public var ScreenImage : unreal.TArray<unreal.UInt8>;
  
}
