/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.oneskylocalizationservice;

@:umodule("OneSkyLocalizationService")
@:glueCppIncludes("Private/OneSkyLocalizationServiceResponseTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FOneSkyCreateProjectGroupResponseBaseLanguage {
  @:uproperty public var region : unreal.FString;
  @:uproperty public var locale : unreal.FString;
  @:uproperty public var local_name : unreal.FString;
  @:uproperty public var english_name : unreal.FString;
  @:uproperty public var code : unreal.FString;
  
}
