/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.netcodeunittest;

/**
  Flags for configuring the minimal client, what parts of the netcode should be enabled etc.
**/
@:umodule("NetcodeUnitTest")
@:glueCppIncludes("Public/NUTEnum.h")
@:uname("EMinClientFlags")
@:class @:uextern @:uenum extern enum EMinClientFlags {
  None;
  
  /**
    Minimal-client netcode functionality
  **/
  AcceptActors;
  
  /**
    Whether or not to accept actor channels (acts as whitelist-only with NotifyAllowNetActor)
  **/
  AcceptRPCs;
  
  /**
    Whether or not to accept execution of any actor RPC's (they are all blocked by default)
  **/
  SendRPCs;
  
  /**
    Whether or not to allow RPC sending (NOT blocked by default, @todo JohnB: Add send hook)
  **/
  SkipControlJoin;
  
  /**
    Whether or not to skip sending NMT_Join upon connect (or NMT_BeaconJoin for beacons)
  **/
  BeaconConnect;
  
  /**
    Minimal-client events
  **/
  NotifyNetActors;
  
  /**
    Whether or not to trigger a 'NotifyNetActor' event, AFTER creation of actor channel actor
  **/
  NotifyProcessNetEvent;
  
  /**
    Debugging
  **/
  DumpReceivedRaw;
  
  /**
    Whether or not to also hex-dump the raw packet receives to the log/log-window
  **/
  DumpSendRaw;
  
  /**
    Whether or not to also hex-dump the raw packet sends to the log/log-window
  **/
  DumpReceivedRPC;
  
  /**
    Whether or not to dump RPC receives (with LogNetTraffic, detects ProcessEvent RPC fail)
  **/
  DumpSendRPC;
  
}
