/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gameplayabilitieseditor;

@:umodule("GameplayAbilitiesEditor")
@:glueCppIncludes("Public/GameplayEffectCreationMenu.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FGameplayEffectCreationData {
  @:uproperty public var ParentGameplayEffect : unreal.TSubclassOf<unreal.gameplayabilities.UGameplayEffect>;
  
  /**
    The default BaseName of the new asset. E.g "Damage" -> GE_Damage or GE_HeroName_AbilityName_Damage
  **/
  @:uproperty public var BaseName : unreal.FString;
  
  /**
    Where to show this in the menu. Use "|" for sub categories. E.g, "Status|Hard|Stun|Root".
  **/
  @:uproperty public var MenuPath : unreal.FString;
  
}
