/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

/**
  Enumeration to determine how a track should be evaluated
**/
@:umodule("MovieScene")
@:glueCppIncludes("Public/Evaluation/MovieSceneEvaluationTrack.h")
@:uname("EEvaluationMethod")
@:class @:uextern @:uenum extern enum EEvaluationMethod {
  
  /**
    Evaluation only ever occurs at a single time. Delta is irrelevant. Example: Basic curve eval, animation
  **/
  Static;
  
  /**
    Evaluation from one frame to the next must consider the entire swept delta range on the track. Example: Events
  **/
  Swept;
  
}
