/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.mediaiocore;

/**
  Configuration of a device input / output.
**/
@:umodule("MediaIOCore")
@:glueCppIncludes("Public/MediaIOCoreDefinitions.h")
@:uextern @:ustruct extern class FMediaIOConfiguration {
  
  /**
    The configuration's video mode.
  **/
  @:uproperty public var MediaMode : unreal.mediaiocore.FMediaIOMode;
  
  /**
    The configuration's device and transport type.
  **/
  @:uproperty public var MediaConnection : unreal.mediaiocore.FMediaIOConnection;
  
  /**
    Configured as an input or output.
  **/
  @:uproperty public var bIsInput : Bool;
  
}
