/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.aimodule;


/**
  Play Sound task node.
  Plays the specified sound when executed.
**/
@:umodule("AIModule")
@:glueCppIncludes("BehaviorTree/Tasks/BTTask_PlaySound.h")
@:uextern extern class UBTTask_PlaySound extends unreal.aimodule.UBTTaskNode {
  
  /**
    CUE to play
  **/
  public var SoundToPlay : unreal.USoundCue;
  
}
