/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.scriptplugin;


/**
  Script-extendable component class
**/
@:glueCppIncludes("ScriptPluginComponent.h")
@:uextern extern class UScriptPluginComponent extends unreal.UActorComponent {
  
  /**
    Calls a script-defined function (no arguments)
    @param FunctionName Name of the function to call
  **/
  public function CallScriptFunction(FunctionName : unreal.FString) : Bool;
  
}
