/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

@:umodule("MovieScene")
@:glueCppIncludes("SequencerSettings.h")
@:uname("EMovieSceneKeyInterpolation")
@:class @:uextern extern enum EMovieSceneKeyInterpolation {
  
  /**
    Auto.
    @DisplayName Auto
  **/
  @DisplayName("Auto")
  Auto;
  
  /**
    User.
    @DisplayName User
  **/
  @DisplayName("User")
  User;
  
  /**
    Break.
    @DisplayName Break
  **/
  @DisplayName("Break")
  Break;
  
  /**
    Linear.
    @DisplayName Linear
  **/
  @DisplayName("Linear")
  Linear;
  
  /**
    Constant.
    @DisplayName Constant
  **/
  @DisplayName("Constant")
  Constant;
  
}
