/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.leapmotion;

@:umodule("LeapMotion")
@:glueCppIncludes("LeapGesture.h")
@:uname("LeapGestureState")
@:uextern extern enum LeapGestureState {
  GESTURE_STATE_INVALID;
  GESTURE_STATE_START;
  GESTURE_STATE_UPDATE;
  GESTURE_STATE_STOP;
  
}
