/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _   _ __   __ 
   * | | | | | | |\ \ / / 
   * | | | | |_| | \ V /  
   * | | | |  _  | /   \  
   * | |_| | | | |/ /^\ \ 
   *  \___/\_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  Settings to allow designers to override the automatic expose
**/
@:glueCppIncludes("Engine/EngineBaseTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FExposureSettings {
  
  /**
    true: fixed exposure using the LogOffset value, false: automatic eye adaptation
  **/
  @:uproperty public var bFixed : Bool;
  
  /**
    usually -4:/16 darker .. +4:16x brighter
  **/
  @:uproperty public var LogOffset : unreal.Int32;
  
}
