/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _   _ __   __ 
   * | | | | | | |\ \ / / 
   * | | | | |_| | \ V /  
   * | | | |  _  | /   \  
   * | |_| | | | |/ /^\ \ 
   *  \___/\_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Materials/MaterialExpressionTextureSampleParameter.h")
@:uextern @:uclass extern class UMaterialExpressionTextureSampleParameter extends unreal.UMaterialExpressionTextureSample {
  
  /**
    The name of the parameter Group to display in MaterialInstance Editor. Default is None group
  **/
  @:uproperty public var Group : unreal.FName;
  
  /**
    GUID that should be unique within the material, this is used for parameter renaming.
  **/
  @:uproperty public var ExpressionGUID : unreal.FGuid;
  @:uproperty public var ParameterName : unreal.FName;
  
}
