/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.magicleap;

/**
  The LightingTrackingComponent wraps the Magic Leap lighting tracking API.
  This api provides lumosity data from the camera that can be used to shade objects in a more realistic
  manner (via the post processor).
**/
@:umodule("MagicLeap")
@:glueCppIncludes("LightingTrackingComponent.h")
@:uextern @:uclass extern class ULightingTrackingComponent extends unreal.UActorComponent {
  
  /**
    Set to true if you want the color temperature value from the cameras to be used in post processing.
  **/
  @:uproperty public var UseColorTemp : Bool;
  
  /**
    Set to true if you want the global ambience value from the cameras to be used in post processing.
  **/
  @:uproperty public var UseGlobalAmbience : Bool;
  
}
