/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.levelsequence;

@:umodule("LevelSequence")
@:glueCppIncludes("LevelSequenceActor.h")
@:uextern @:uclass extern class ULevelSequenceBurnInOptions extends unreal.UObject {
  
  /**
    Loads the specified class path and initializes an instance, then stores it in Settings.
  **/
  @:ufunction(BlueprintCallable) @:final public function SetBurnIn(InBurnInClass : unreal.FSoftClassPath) : Void;
  @:uproperty public var Settings : unreal.levelsequence.ULevelSequenceBurnInInitSettings;
  @:uproperty public var BurnInClass : unreal.FSoftClassPath;
  @:uproperty public var bUseBurnIn : Bool;
  
}
