/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.enginesettings;

@:umodule("EngineSettings")
@:glueCppIncludes("HudSettings.h")
@:uextern extern class UHudSettings extends unreal.UObject {
  
  /**
    Collection of names specifying what debug info to display for ViewTarget actor.
  **/
  public var DebugDisplay : unreal.TArray<unreal.FName>;
  
  /**
    Whether the HUD is visible at all.
  **/
  public var bShowHUD : Bool;
  
}
