/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _   _ __   __ 
   * | | | | | | |\ \ / / 
   * | | | | |_| | \ V /  
   * | | | |  _  | /   \  
   * | |_| | | | |/ /^\ \ 
   *  \___/\_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  
**/
@:umodule("UnrealEd")
@:glueCppIncludes("UserDefinedStructure/UserDefinedStructEditorData.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FStructVariableDescription {
  @:uproperty public var bEnable3dWidget : Bool;
  @:uproperty public var bEnableMultiLineText : Bool;
  @:uproperty public var bDontEditoOnInstance : Bool;
  @:uproperty public var ToolTip : unreal.FString;
  
  /**
    CurrentDefaultValue stores the actual default value, after the DefaultValue was changed, and before the struct was recompiled
  **/
  @:uproperty public var CurrentDefaultValue : unreal.FString;
  @:uproperty public var bInvalidMember : Bool;
  @:uproperty public var bIsMap : Bool;
  @:uproperty public var bIsSet : Bool;
  @:uproperty public var bIsArray : Bool;
  @:uproperty public var PinValueType : unreal.FEdGraphTerminalType;
  @:uproperty public var SubCategory : unreal.FString;
  
  /**
    TYPE DATA
  **/
  @:uproperty public var Category : unreal.FString;
  @:uproperty public var DefaultValue : unreal.FString;
  @:uproperty public var FriendlyName : unreal.FString;
  @:uproperty public var VarGuid : unreal.FGuid;
  @:uproperty public var VarName : unreal.FName;
  
}
