/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.addcontentdialog;

/**
  Structure that defines a shared feature pack resource.
**/
@:umodule("AddContentDialog")
@:glueCppIncludes("Public/FeaturePackContentSource.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FFeatureAdditionalFiles {
  
  /**
    List of files to insert
  **/
  @:uproperty public var AdditionalFilesList : unreal.TArray<unreal.FString>;
  
  /**
    Name of the folder to insert the files to
  **/
  @:uproperty public var DestinationFilesFolder : unreal.FString;
  
}
