/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  @TODO: this can encapsulate globally defined fields as well (like with native
         delegate signatures); consider renaming to FFieldReference
**/
@:glueCppIncludes("Classes/Engine/MemberReference.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMemberReference {
  
  /**
    The Guid of the variable
  **/
  @:uproperty private var MemberGuid : unreal.FGuid;
  
  /**
    Name of variable
  **/
  @:uproperty private var MemberName : unreal.FName;
  @:uproperty private var MemberScope : unreal.FString;
  
  /**
    Most often the Class that this member is defined in. Could be a UPackage
    if it is a native delegate signature function (declared globally). Should
    be NULL if bSelfContext is true.
  **/
  @:uproperty private var MemberParent : unreal.UObject;
  
}
