/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.environmentqueryeditor;

@:umodule("EnvironmentQueryEditor")
@:glueCppIncludes("EnvironmentQueryGraphNode_Test.h")
@:uextern extern class UEnvironmentQueryGraphNode_Test extends unreal.environmentqueryeditor.UEnvironmentQueryGraphNode {
  
  /**
    toggles test
  **/
  public var bTestEnabled : Bool;
  
  /**
    weight is passed as named param
  **/
  public var bHasNamedWeight : Bool;
  
  /**
    weight percent for display
  **/
  public var TestWeightPct : unreal.Float32;
  
}
