/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.inputcore;


/**
  The number of entries in ETouchIndex must match the number of touch keys defined in EKeys and NUM_TOUCH_KEYS above
**/
@:umodule("InputCore")
@:glueCppIncludes("GameFramework/Actor.h")
@:uname("ETouchIndex.Type")
@:uextern extern enum ETouchIndex {
  Touch1;
  Touch2;
  Touch3;
  Touch4;
  Touch5;
  Touch6;
  Touch7;
  Touch8;
  Touch9;
  Touch10;
  
}
