/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.gameplayabilities;

@:umodule("GameplayAbilities")
@:glueCppIncludes("AbilitySystemTestPawn.h")
@:uextern extern class AAbilitySystemTestPawn extends unreal.ADefaultPawn implements unreal.gameplayabilities.IGameplayCueInterface implements unreal.gameplayabilities.IAbilitySystemInterface {
  public var AbilitySystemComponent : unreal.gameplayabilities.UAbilitySystemComponent;
  
}
