/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.animgraphruntime;

@:umodule("AnimGraphRuntime")
@:glueCppIncludes("Public/BoneControllers/AnimNode_LegIK.h")
@:uextern @:ustruct extern class FAnimNode_LegIK extends unreal.animgraphruntime.FAnimNode_SkeletalControlBase {
  @:uproperty public var LegsDefinition : unreal.TArray<unreal.animgraphruntime.FAnimLegIKDefinition>;
  
  /**
    Max Number of Iterations.
  **/
  @:uproperty public var MaxIterations : unreal.Int32;
  
  /**
    Tolerance for reaching IK Target, in unreal units.
  **/
  @:uproperty public var ReachPrecision : unreal.Float32;
  
}
