/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.landscapeeditor;

@:umodule("LandscapeEditor")
@:glueCppIncludes("Public/LandscapeEditorObject.h")
@:uname("ELandscapeMirrorOperation")
@:class @:uextern @:uenum extern enum ELandscapeMirrorOperation {
  
  /**
    -X to +X
  **/
  @DisplayName("-X to +X")
  MinusXToPlusX;
  
  /**
    +X to -X
  **/
  @DisplayName("+X to -X")
  PlusXToMinusX;
  
  /**
    -Y to +Y
  **/
  @DisplayName("-Y to +Y")
  MinusYToPlusY;
  
  /**
    +Y to -Y
  **/
  @DisplayName("+Y to -Y")
  PlusYToMinusY;
  
  /**
    Rotate -X to +X
  **/
  @DisplayName("Rotate -X to +X")
  RotateMinusXToPlusX;
  
  /**
    Rotate +X to -X
  **/
  @DisplayName("Rotate +X to -X")
  RotatePlusXToMinusX;
  
  /**
    Rotate -Y to +Y
  **/
  @DisplayName("Rotate -Y to +Y")
  RotateMinusYToPlusY;
  
  /**
    Rotate +Y to -Y
  **/
  @DisplayName("Rotate +Y to -Y")
  RotatePlusYToMinusY;
  
}
