/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.hardwaretargeting;

/**
  Enum specifying a class of hardware
**/
@:umodule("HardwareTargeting")
@:glueCppIncludes("Public/HardwareTargetingSettings.h")
@:uname("EHardwareClass.Type")
@:uextern @:uenum extern enum EHardwareClass {
  
  /**
    Unspecified, meaning no choice has been made yet
  **/
  Unspecified;
  
  /**
    Desktop or console
  **/
  Desktop;
  
  /**
    Mobile or tablet
  **/
  Mobile;
  
}
