/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.landscape;

@:umodule("Landscape")
@:glueCppIncludes("Classes/LandscapeProxy.h")
@:uname("ELandscapeLODFalloff.Type")
@:uextern @:uenum extern enum ELandscapeLODFalloff {
  
  /**
    Default mode.
    @DisplayName Linear
  **/
  @DisplayName("Linear")
  Linear;
  
  /**
    Square Root give more natural transition, and also keep the same LOD.
    @DisplayName Square Root
  **/
  @DisplayName("Square Root")
  SquareRoot;
  
}
