/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.blueprintgraph;

@:umodule("BlueprintGraph")
@:glueCppIncludes("K2Node_FunctionTerminator.h")
@:uextern extern class UK2Node_FunctionTerminator extends unreal.blueprintgraph.UK2Node_EditablePinBase {
  
  /**
    The name of the signature function.
  **/
  public var SignatureName : unreal.FName;
  
  /**
    The source class that defines the signature, if it is getting that from elsewhere (e.g. interface, base class etc).
    If NULL, this is a newly created function.
  **/
  public var SignatureClass : unreal.TSubclassOf<unreal.UObject>;
  
}
