/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Sound/SoundMix.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FAudioEQEffect {
  
  /**
    Bandwidth of band 3. Region is center frequency +/- Bandwidth /2
  **/
  @:uproperty public var Bandwidth3 : unreal.Float32;
  
  /**
    Boost/cut of band 3
  **/
  @:uproperty public var Gain3 : unreal.Float32;
  
  /**
    Center frequency in Hz for band 3
  **/
  @:uproperty public var FrequencyCenter3 : unreal.Float32;
  
  /**
    Bandwidth of band 2. Region is center frequency +/- Bandwidth /2
  **/
  @:uproperty public var Bandwidth2 : unreal.Float32;
  
  /**
    Boost/cut of band 2
  **/
  @:uproperty public var Gain2 : unreal.Float32;
  
  /**
    Center frequency in Hz for band 2
  **/
  @:uproperty public var FrequencyCenter2 : unreal.Float32;
  
  /**
    Bandwidth of band 1. Region is center frequency +/- Bandwidth /2
  **/
  @:uproperty public var Bandwidth1 : unreal.Float32;
  
  /**
    Boost/cut of band 1
  **/
  @:uproperty public var Gain1 : unreal.Float32;
  
  /**
    Center frequency in Hz for band 1
  **/
  @:uproperty public var FrequencyCenter1 : unreal.Float32;
  
  /**
    Bandwidth of band 0. Region is center frequency +/- Bandwidth /2
  **/
  @:uproperty public var Bandwidth0 : unreal.Float32;
  
  /**
    Boost/cut of band 0
  **/
  @:uproperty public var Gain0 : unreal.Float32;
  
  /**
    Center frequency in Hz for band 0
  **/
  @:uproperty public var FrequencyCenter0 : unreal.Float32;
  
}
