/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Tick function that calls UPrimitiveComponent::PostPhysicsTick
  //DEPRECATED: This struct has been deprecated. Please use your own tick functions if you need something other than the primary tick function
**/
@:glueCppIncludes("Classes/Engine/EngineBaseTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FPrimitiveComponentPostPhysicsTickFunction extends unreal.FTickFunction {
  
}
