/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Used by UUIString::WrapString to track information about each line that is generated as the result of wrapping.
**/
@:glueCppIncludes("Public/CanvasTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FWrappedStringElement {
  
  /**
    the size (in pixels) that it will take to render this string
  **/
  @:uproperty public var LineExtent : unreal.FVector2D;
  
  /**
    the string associated with this line
  **/
  @:uproperty public var Value : unreal.FString;
  
}
