/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Component to handle receiving notifications from the OS about platform events.
**/
@:glueCppIncludes("Components/PlatformEventsComponent.h")
@:uextern @:uclass extern class UPlatformEventsComponent extends unreal.UActorComponent {
  
  /**
    Check whether a convertible laptop is laptop mode.
    
    @return true if in laptop mode, false otherwise or if not a convertible laptop.
    @see IsInTabletMode, SupportsConvertibleLaptops
  **/
  @:ufunction(BlueprintCallable) @:final public function IsInLaptopMode() : Bool;
  
  /**
    Check whether a convertible laptop is laptop mode.
    
    @return true if in tablet mode, false otherwise or if not a convertible laptop.
    @see IsInLaptopMode, SupportsConvertibleLaptops
  **/
  @:ufunction(BlueprintCallable) @:final public function IsInTabletMode() : Bool;
  
  /**
    Check whether the platform supports convertible laptops.
    
    Note: This does not necessarily mean that the platform is a convertible laptop.
    For example, convertible laptops running Windows 7 or older will return false,
    and regular laptops running Windows 8 or newer will return true.
    
    @return true for convertible laptop platforms, false otherwise.
    @see IsInLaptopMode, IsInTabletMode
  **/
  @:ufunction(BlueprintCallable) @:final public function SupportsConvertibleLaptops() : Bool;
  
  /**
    This is called when a convertible laptop changed into tablet mode.
  **/
  @:uproperty public var PlatformChangedToTabletModeDelegate : unreal.FPlatformEventDelegate;
  
  /**
    This is called when a convertible laptop changed into laptop mode.
  **/
  @:uproperty public var PlatformChangedToLaptopModeDelegate : unreal.FPlatformEventDelegate;
  
}
