/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.animgraph;

@:umodule("AnimGraph")
@:glueCppIncludes("K2Node_TransitionRuleGetter.h")
@:uname("ETransitionGetter.Type")
@:uextern extern enum ETransitionGetter {
  AnimationAsset_GetCurrentTime;
  AnimationAsset_GetLength;
  AnimationAsset_GetCurrentTimeFraction;
  AnimationAsset_GetTimeFromEnd;
  AnimationAsset_GetTimeFromEndFraction;
  CurrentState_ElapsedTime;
  CurrentState_GetBlendWeight;
  CurrentTransitionDuration;
  ArbitraryState_GetBlendWeight;
  
}
