/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

@:umodule("UnrealEd")
@:glueCppIncludes("Settings/EditorProjectSettings.h")
@:uextern @:uclass extern class UBlueprintEditorProjectSettings extends unreal.UDeveloperSettings {
  
  /**
    List of compiler messages that have been suppressed completely - message suppression is only
    advisable when using blueprints that you cannot update and are raising innocuous warnings.
    If useless messages are being raised prefer to contact support rather than disabling messages
  **/
  @:uproperty public var DisabledCompilerMessages : unreal.TArray<unreal.FName>;
  
  /**
    List of compiler messages that have been suppressed outside of full, interactive editor sessions for
    the current project - useful for silencing warnings that were added to the engine after
    project inception and are going to be addressed as they are found by content authors
  **/
  @:uproperty public var DisabledCompilerMessagesExceptEditor : unreal.TArray<unreal.FName>;
  
  /**
    If enabled, the editor will load packages to look for soft references to actors when deleting/renaming them. This can be slow in large projects so disable this to improve performance but increase the chance of breaking blueprints/sequences that use soft actor references
  **/
  @:uproperty public var bValidateUnloadedSoftActorReferences : Bool;
  
  /**
    Flag to disable faster compiles for individual blueprints if they have no function signature
    changes. This flag is deprecated! In 4.21 there will be no way to force all dependencies to
    compile when no changes are detected. Report any issues immediately.
  **/
  @:uproperty public var bForceAllDependenciesToRecompile : Bool;
  
  /**
    Flag to disable the compilation manager for blueprints - requires editor restart.
    This flag is deprecated! In 4.21 the compilation manager will be the only way to compile
    blueprints. Report any compilation manager issues immediately.
  **/
  @:uproperty public var bDisableCompilationManager : Bool;
  
}
