/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.leapmotion;

@:umodule("LeapMotion")
@:glueCppIncludes("Public/LeapMotionData.h")
@:uname("ELeapTrackingFidelity")
@:uextern @:uenum extern enum ELeapTrackingFidelity {
  LEAP_LOW_LATENCY;
  LEAP_NORMAL;
  LEAP_SMOOTH;
  LEAP_CUSTOM;
  
}
