/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.editor;

@:umodule("UnrealEd")
@:glueCppIncludes("Factories/FbxMeshImportData.h")
@:uname("EFBXNormalImportMethod")
@:uextern extern enum EFBXNormalImportMethod {
  
  /**
    Compute Normals
  **/
  @DisplayName("Compute Normals")
  FBXNIM_ComputeNormals;
  
  /**
    Import Normals
  **/
  @DisplayName("Import Normals")
  FBXNIM_ImportNormals;
  
  /**
    Import Normals and Tangents
  **/
  @DisplayName("Import Normals and Tangents")
  FBXNIM_ImportNormalsAndTangents;
  
}
