/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.editor;


/**
  Import data and options used when importing a static mesh from fbx
**/
@:umodule("UnrealEd")
@:glueCppIncludes("Factories/FbxSkeletalMeshImportData.h")
@:uextern extern class UFbxSkeletalMeshImportData extends unreal.editor.UFbxMeshImportData {
  
  /**
    If checked, do not filter same vertices. Keep all vertices even if they have exact same properties
  **/
  public var bKeepOverlappingVertices : Bool;
  
  /**
    If enabled, creates Unreal morph objects for the imported meshes
  **/
  public var bImportMorphTargets : Bool;
  
  /**
    If checked, meshes nested in bone hierarchies will be imported instead of being converted to bones.
  **/
  public var bImportMeshesInBoneHierarchy : Bool;
  
  /**
    If checked, triangles with non-matching smoothing groups will be physically split.
  **/
  public var bPreserveSmoothingGroups : Bool;
  
  /**
    Enable this option to use frame 0 as reference pose
  **/
  public var bUseT0AsRefPose : Bool;
  
  /**
    If enabled, update the Skeleton (of the mesh being imported)'s reference pose.
  **/
  public var bUpdateSkeletonReferencePose : Bool;
  
}
