/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.editor;

@:umodule("UnrealEd")
@:glueCppIncludes("ThumbnailRendering/ParticleSystemThumbnailRenderer.h")
@:uextern extern class UParticleSystemThumbnailRenderer extends unreal.editor.UTextureThumbnailRenderer {
  public var OutOfDate : unreal.UTexture2D;
  public var NoImage : unreal.UTexture2D;
  
}
