/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.androidplatformeditor;


/**
  Implements the settings for the Android SDK setup.
**/
@:glueCppIncludes("Private/AndroidSDKSettings.h")
@:uextern extern class UAndroidSDKSettings extends unreal.UObject {
  
  /**
    Which NDK to compile with (a specific version or (without quotes) 'latest' for latest version on disk). Note that choosing android-21 or later won't run on pre-5.0 devices.
  **/
  public var NDKAPILevel : unreal.FString;
  
  /**
    Which SDK to package and compile Java with (a specific version or (without quotes) 'latest' for latest version on disk, or 'matchndk' to match the NDK API Level)
  **/
  public var SDKAPILevel : unreal.FString;
  
  /**
    Location on disk of Java (falls back to JAVA_HOME environment variable if this is left blank)
  **/
  public var JavaPath : unreal.FDirectoryPath;
  
  /**
    Location on disk of the ANT tool (falls back to ANT_HOME environment variable if this is left blank)
  **/
  public var ANTPath : unreal.FDirectoryPath;
  
  /**
    Location on disk of the Android NDK (falls back to NDKROOT environment variable if this is left blank)
  **/
  public var NDKPath : unreal.FDirectoryPath;
  
  /**
    Location on disk of the Android SDK (falls back to ANDROID_HOME environment variable if this is left blank)
  **/
  public var SDKPath : unreal.FDirectoryPath;
  
}
