/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.synthesis;

@:umodule("Synthesis")
@:glueCppIncludes("Classes/SourceEffects/SourceEffectRingModulation.h")
@:uextern @:ustruct extern class FSourceEffectRingModulationSettings {
  
  /**
    Gain for the wet signal (with ring mod)
  **/
  @:uproperty public var WetLevel : unreal.Float32;
  
  /**
    Gain for the dry signal (no ring mod)
  **/
  @:uproperty public var DryLevel : unreal.Float32;
  
  /**
    Ring modulation depth
  **/
  @:uproperty public var Depth : unreal.Float32;
  
  /**
    Ring modulation frequency
  **/
  @:uproperty public var Frequency : unreal.Float32;
  
  /**
    Ring modulation modulator oscillator type
  **/
  @:uproperty public var ModulatorType : unreal.synthesis.ERingModulatorTypeSourceEffect;
  
}
