/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Indicates how animation should be evaluated between keys.
**/
@:glueCppIncludes("Public/Animation/AnimTypes.h")
@:uname("EAnimInterpolationType")
@:class @:uextern @:uenum extern enum EAnimInterpolationType {
  
  /**
    Linear interpolation when looking up values between keys.
    @DisplayName Linear
  **/
  @DisplayName("Linear")
  Linear;
  
  /**
    Step interpolation when looking up values between keys.
    @DisplayName Step
  **/
  @DisplayName("Step")
  Step;
  
}
