/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  PhysicsBody options when bone is hidden
**/
@:glueCppIncludes("Classes/Components/SkinnedMeshComponent.h")
@:uname("EPhysBodyOp")
@:uextern @:uenum extern enum EPhysBodyOp {
  
  /**
    Don't do anything.
  **/
  PBO_None;
  
  /**
    Terminate - if you terminate, you won't be able to re-init when unhidden.
  **/
  PBO_Term;
  PBO_MAX;
  
}
