/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

/**
  Network settings.
**/
@:glueCppIncludes("Engine/NetworkSettings.h")
@:uextern @:uclass extern class UNetworkSettings extends unreal.UDeveloperSettings {
  
  /**
    Maximum allowable size for replicated dynamic arrays (in bytes).  Must be between 1 and 65535.
  **/
  @:uproperty public var MaxRepArrayMemory : unreal.Int32;
  
  /**
    Maximum allowable size for replicated dynamic arrays (in number of elements). Must be between 1 and 65535.
  **/
  @:uproperty public var MaxRepArraySize : unreal.Int32;
  
  /**
    If true, origin rebasing is enabled in multiplayer games, meaning that servers and clients can have different local world origins.
  **/
  @:uproperty public var bEnableMultiplayerWorldOriginRebasing : Bool;
  
  /**
    If true, libcurl authenticates the peer's certificate. Disable to allow self-signed certificates.
  **/
  @:uproperty public var bVerifyPeer : Bool;
  
}
