/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.gameplaydebugger;

@:umodule("GameplayDebugger")
@:glueCppIncludes("GameplayDebuggingHUDComponent.h")
@:uextern extern class AGameplayDebuggingHUDComponent extends unreal.AActor {
  private var PlayerOwner : unreal.APlayerController;
  private var Canvas : unreal.UCanvas;
  public var DebugInfoStartY : unreal.Float32;
  public var DebugInfoStartX : unreal.Float32;
  public var MenuStartY : unreal.Float32;
  public var MenuStartX : unreal.Float32;
  
}
