/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.apexdestruction;

/**
  Parameters that pertain to chunk debris-level settings.
**/
@:umodule("ApexDestruction")
@:glueCppIncludes("Public/DestructibleMesh.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FDestructibleDebrisParameters {
  
  /**
    "Debris chunks" (see debrisDepth, above) will be destroyed if they leave this box.
    The box translates with the destructible actor's initial position, but does not
    rotate or scale.
  **/
  @:uproperty public var ValidBounds : unreal.FBox;
  @:uproperty public var DebrisMaxSeparationMax : unreal.Float32;
  
  /**
    "Debris chunks" (see debrisDepth, above) will be destroyed if they are separated from
    their origin by a distance greater than maxSeparation.  The actual maxSeparation is
    interpolated between these two values, based upon the module's LOD setting.  To disable
    maxSeparation, clear the bDebrisMaxSeparation flag in the flags field.
    If debrisMaxSeparationMax < debrisMaxSeparationMin, the mean of the two is used for both.
    Default debrisMaxSeparationMin = 1.0, debrisMaxSeparationMax = 10.0f.
  **/
  @:uproperty public var DebrisMaxSeparationMin : unreal.Float32;
  @:uproperty public var DebrisLifetimeMax : unreal.Float32;
  
  /**
    "Debris chunks" (see debrisDepth, above) will be destroyed after a time (in seconds)
    separated from non-debris chunks.  The actual lifetime is interpolated between these
    two bDebrisTimeout, based upon the module's LOD setting.  To disable lifetime, clear the
    bDebrisTimeout flag in the flags field.
    If debrisLifetimeMax < debrisLifetimeMin, the mean of the two is used for both.
    Default debrisLifetimeMin = 1.0, debrisLifetimeMax = 10.0f.
  **/
  @:uproperty public var DebrisLifetimeMin : unreal.Float32;
  
}
