/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.aimodule;

@:umodule("AIModule")
@:glueCppIncludes("Actions/PawnActionsComponent.h")
@:uextern @:uclass extern class UPawnActionsComponent extends unreal.UActorComponent {
  @:uproperty private var CurrentAction : unreal.aimodule.UPawnAction;
  @:uproperty private var ActionEvents : unreal.TArray<unreal.aimodule.FPawnActionEvent>;
  @:uproperty private var ActionStacks : unreal.TArray<unreal.aimodule.FPawnActionStack>;
  @:uproperty private var ControlledPawn : unreal.APawn;
  
  /**
    blueprint interface
  **/
  @:ufunction(BlueprintCallable) static public function K2_PerformAction(Pawn : unreal.APawn, Action : unreal.aimodule.UPawnAction, Priority : unreal.aimodule.EAIRequestPriority = HardScript) : Bool;
  @:ufunction(BlueprintCallable) @:final public function K2_PushAction(NewAction : unreal.aimodule.UPawnAction, Priority : unreal.aimodule.EAIRequestPriority, @:opt("None") Instigator : unreal.UObject) : Bool;
  
  /**
    Aborts given action instance
  **/
  @:ufunction(BlueprintCallable) @:final public function K2_AbortAction(ActionToAbort : unreal.aimodule.UPawnAction) : unreal.aimodule.EPawnActionAbortState;
  
  /**
    Aborts given action instance
  **/
  @:ufunction(BlueprintCallable) @:final public function K2_ForceAbortAction(ActionToAbort : unreal.aimodule.UPawnAction) : unreal.aimodule.EPawnActionAbortState;
  
}
