/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.mediaassets;

/**
  A media source that selects other media sources based on target platform.
  
  Use this asset to override media sources on a per-platform basis.
**/
@:umodule("MediaAssets")
@:glueCppIncludes("PlatformMediaSource.h")
@:uextern @:uclass extern class UPlatformMediaSource extends unreal.mediaassets.UMediaSource {
  
}
