/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.destructiblemesheditor;

@:umodule("DestructibleMeshEditor")
@:glueCppIncludes("DestructibleChunkParamsProxy.h")
@:uextern extern class UDestructibleChunkParamsProxy extends unreal.UObject {
  public var ChunkParams : unreal.FDestructibleChunkParameters;
  public var ChunkIndex : unreal.Int32;
  public var DestructibleMesh : unreal.UDestructibleMesh;
  
}
