/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.vpbookmarkeditor;

@:umodule("VPBookmarkEditor")
@:glueCppIncludes("VPBookmarkEditorBlueprintLibrary.h")
@:uextern @:uclass extern class UVPBookmarkEditorBlueprintLibrary extends unreal.UBlueprintFunctionLibrary {
  @:ufunction(BlueprintCallable) static public function JumpToBookmarkInLevelEditor(Bookmark : unreal.Const<unreal.vpbookmark.UVPBookmark>) : Bool;
  @:ufunction(BlueprintCallable) static public function JumpToBookmarkInLevelEditorByIndex(BookmarkIndex : unreal.Int32) : Bool;
  @:ufunction(BlueprintCallable) static public function AddBookmarkAtCurrentLevelEditorPosition(ActorClass : unreal.Const<unreal.TSubclassOf<unreal.AActor>>, CreationContext : unreal.Const<unreal.vpbookmark.FVPBookmarkCreationContext>, Offset : unreal.Const<unreal.FVector>, bFlattenRotation : Bool = true) : unreal.AActor;
  @:ufunction(BlueprintCallable) static public function GetAllActorsClassThamImplementsVPBookmarkInterface(OutActorClasses : unreal.PRef<unreal.TArray<unreal.TSubclassOf<unreal.AActor>>>) : Void;
  
}
