/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _   _ __   __ 
   * | | | | | | |\ \ / / 
   * | | | | |_| | \ V /  
   * | | | |  _  | /   \  
   * | |_| | | | |/ /^\ \ 
   *  \___/\_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  MovieSceneSpawnable describes an object that can be spawned for this MovieScene
**/
@:umodule("MovieScene")
@:glueCppIncludes("MovieSceneSpawnable.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FMovieSceneSpawnable {
  #if WITH_EDITORONLY_DATA
  
  /**
    Deprecated generated class
  **/
  @:deprecated @:uproperty public var GeneratedClass_DEPRECATED : unreal.UClass;
  #end // WITH_EDITORONLY_DATA
  
}
