/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.editor;

/**
  Types of primitives for drawing thumbnails of resources.
**/
@:umodule("UnrealEd")
@:glueCppIncludes("Classes/ThumbnailRendering/ThumbnailManager.h")
@:uname("EThumbnailPrimType")
@:uextern @:uenum extern enum EThumbnailPrimType {
  TPT_None;
  TPT_Sphere;
  TPT_Cube;
  TPT_Plane;
  TPT_Cylinder;
  TPT_MAX;
  
}
