/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.landscapeeditor;


/**
  Temp
**/
@:umodule("LandscapeEditor")
@:glueCppIncludes("LandscapeEditorObject.h")
@:uname("ELandscapeToolNoiseMode.Type")
@:uextern extern enum ELandscapeToolNoiseMode {
  
  /**
    Noise will both raise and lower the heightmap
  **/
  Both;
  
  /**
    Noise will only raise the heightmap
  **/
  Raise;
  
  /**
    Noise will only lower the heightmap
  **/
  Lower;
  
}
