/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.sequencer;


/**
  Serializable options for sequencer.
**/
@:umodule("Sequencer")
@:glueCppIncludes("Private/SequencerSettings.h")
@:uextern extern class USequencerSettings extends unreal.UObject {
  private var CurveValueSnapInterval : unreal.Float32;
  private var TimeSnapInterval : unreal.Float32;
  
}
