/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  A sound actor that can be placed in a level
**/
@:glueCppIncludes("Sound/AmbientSound.h")
@:uextern extern class AAmbientSound extends unreal.AActor {
  public var AudioComponent : unreal.UAudioComponent;
  
}
