/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  
**/
@:glueCppIncludes("Particles/EmitterCameraLensEffectBase.h")
@:uextern extern class AEmitterCameraLensEffectBase extends unreal.AEmitter {
  
  /**
    Camera this emitter is attached to, will be notified when emitter is destroyed
  **/
  private var BaseCamera : unreal.APlayerCameraManager;
  
  /**
    If an emitter class in this array is currently playing, do not play this effect.
    Useful for preventing multiple similar or expensive camera effects from playing simultaneously.
  **/
  public var EmittersToTreatAsSame : unreal.TArray<unreal.TSubclassOf<unreal.AEmitterCameraLensEffectBase>>;
  
  /**
    true if multiple instances of this emitter can exist simultaneously, false otherwise.
  **/
  public var bAllowMultipleInstances : Bool;
  
  /**
    How far in front of the camera this emitter should live, assuming an FOV of 80 degrees.
    Note that the actual distance will be automatically adjusted to account for the actual FOV.
  **/
  public var DistFromCamera : unreal.Float32;
  
  /**
    In order to get the particle effect looking correct we need to have a base FOV which we just to move the particle closer/further from the camera *
  **/
  public var BaseFOV : unreal.Float32;
  
  /**
    The effect to use for non extreme content
  **/
  private var PS_CameraEffectNonExtremeContent : unreal.UParticleSystem;
  
  /**
    Particle System to use
  **/
  private var PS_CameraEffect : unreal.UParticleSystem;
  
}
