/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  Info is the base class of an Actor that isn't meant to have a physical representation in the world, used primarily
  for "manager" type classes that hold settings data about the world, but might need to be an Actor for replication purposes.
**/
@:glueCppIncludes("GameFramework/Info.h")
@:uextern extern class AInfo extends unreal.AActor {
  #if WITH_EDITORONLY_DATA
  public var SpriteComponent : unreal.UBillboardComponent;
  #end // WITH_EDITORONLY_DATA
  
}
