/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  Indicates how animation should be evaluated between keys.
**/
@:glueCppIncludes("Animation/AnimSequence.h")
@:uname("EAnimInterpolationType")
@:class @:uextern extern enum EAnimInterpolationType {
  
  /**
    Linear interpolation when looking up values between keys.
    @DisplayName Linear
  **/
  @DisplayName("Linear")
  Linear;
  
  /**
    Step interpolation when looking up values between keys.
    @DisplayName Step
  **/
  @DisplayName("Step")
  Step;
  
}
