/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Bone translation retargeting mode.
**/
@:glueCppIncludes("Animation/Skeleton.h")
@:uname("EBoneTranslationRetargetingMode.Type")
@:uextern extern enum EBoneTranslationRetargetingMode {
  
  /**
    Use translation from animation data.
  **/
  Animation;
  
  /**
    Use fixed translation from Skeleton.
  **/
  Skeleton;
  
  /**
    Use Translation from animation, but scale length by Skeleton's proportions.
  **/
  AnimationScaled;
  
  /**
    Use Translation from animation, but also play the difference from retargeting pose as an additive.
  **/
  AnimationRelative;
  
}
