/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  EInputEvent
**/
@:glueCppIncludes("Engine/InputActionDelegateBinding.h")
@:uname("EInputEvent")
@:uextern extern enum EInputEvent {
  IE_Pressed;
  IE_Released;
  IE_Repeat;
  IE_DoubleClick;
  IE_Axis;
  
}
