/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Controls the way that the width scale property affects animation trails.
**/
@:glueCppIncludes("Particles/ParticleSystemComponent.h")
@:uname("ETrailWidthMode")
@:uextern extern enum ETrailWidthMode {
  
  /**
    From Centre
  **/
  @DisplayName("From Centre")
  ETrailWidthMode_FromCentre;
  
  /**
    From First Socket
  **/
  @DisplayName("From First Socket")
  ETrailWidthMode_FromFirst;
  
  /**
    From Second Socket
  **/
  @DisplayName("From Second Socket")
  ETrailWidthMode_FromSecond;
  
}
