/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Enum to specify which axis to use for the forward vector when using TRISORT_CustomLeftRight sort mode.
**/
@:glueCppIncludes("Engine/SkeletalMesh.h")
@:uname("ETriangleSortAxis")
@:uextern extern enum ETriangleSortAxis {
  TSA_X_Axis;
  TSA_Y_Axis;
  TSA_Z_Axis;
  
}
