/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  
**/
@:glueCppIncludes("Animation/AnimSequenceBase.h")
@:noCopy @:noEquals @:uextern extern class FTransformCurve extends unreal.FAnimCurveBase {
  public var ScaleCurve : unreal.FVectorCurve;
  
  /**
    Rotation curve - right now we use euler because quat also doesn't provide linear interpolation - curve editor can't handle quat interpolation
    If you hit gimbal lock, you should add extra key to fix it. This will cause gimbal lock.
    @TODO: Eventually we'll need FRotationCurve that would contain rotation curve - that will interpolate as slerp or as quaternion
  **/
  public var RotationCurve : unreal.FVectorCurve;
  
  /**
    Curve data for each transform.
  **/
  public var TranslationCurve : unreal.FVectorCurve;
  
}
