/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Animation/AnimCompress_RemoveTrivialKeys.h")
@:uextern extern class UAnimCompress_RemoveTrivialKeys extends unreal.UAnimCompress {
  public var MaxScaleDiff : unreal.Float32;
  public var MaxAngleDiff : unreal.Float32;
  public var MaxPosDiff : unreal.Float32;
  
}
