/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  Defines a curve of interpolated points to evaluate over a given range
**/
@:glueCppIncludes("Curves/CurveBase.h")
@:uextern extern class UCurveBase extends unreal.UObject {
  
  /**
    Get the time range across all curves
  **/
  @:thisConst @:final public function GetTimeRange(MinTime : unreal.Float32, MaxTime : unreal.Float32) : Void;
  
  /**
    Get the value range across all curves
  **/
  @:thisConst @:final public function GetValueRange(MinValue : unreal.Float32, MaxValue : unreal.Float32) : Void;
  #if WITH_EDITORONLY_DATA
  
  /**
    The filename imported to create this object. Relative to this object's package, BaseDir() or absolute
  **/
  public var ImportPath_DEPRECATED : unreal.FString;
  public var AssetImportData : unreal.UAssetImportData;
  #end // WITH_EDITORONLY_DATA
  
}
