/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Engine/InputKeyDelegateBinding.h")
@:uextern extern class UInputKeyDelegateBinding extends unreal.UInputDelegateBinding {
  public var InputKeyDelegateBindings : unreal.TArray<unreal.FBlueprintInputKeyDelegateBinding>;
  
}
