/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, its properties/methods are inaccessible
  
  
**/
@:glueCppIncludes("Matinee/InterpTrackInstBoolProp.h")
@:noClass @:uextern extern class UInterpTrackInstBoolProp extends unreal.UInterpTrackInstProperty {
  
  /**
    Saved value for restoring state when exiting Matinee.
  **/
  public var ResetBool : Bool;
  
  /**
    Mask that indicates which bit the boolean property actually uses of the value pointed to by BoolProp.
  **/
  public var BoolProperty : unreal.UBoolProperty;
  
}
