/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  A level blueprint is a specialized type of blueprint. It is used to house
  global, level-wide logic. In a level blueprint, you can operate on specific
  level-actor instances through blueprint's node-based interface. UE3 users
  should be familiar with this concept, as it is very similar to Kismet.
  
  @see https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/Types/LevelBlueprint/index.html
  @see https://docs.unrealengine.com/latest/INT/Engine/Blueprints/index.html
  @see UBlueprint
  @see ALevelScriptActor
**/
@:glueCppIncludes("Engine/LevelScriptBlueprint.h")
@:uextern extern class ULevelScriptBlueprint extends unreal.UBlueprint {
  #if WITH_EDITORONLY_DATA
  
  /**
    The friendly name to use for UI
  **/
  public var FriendlyName : unreal.FString;
  #end // WITH_EDITORONLY_DATA
  
}
