/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Materials/MaterialExpressionNoise.h")
@:uextern extern class UMaterialExpressionNoise extends unreal.UMaterialExpression {
  
  /**
    usually 2 but higher values allow efficient use of few levels
  **/
  public var LevelScale : unreal.Float32;
  public var OutputMax : unreal.Float32;
  public var OutputMin : unreal.Float32;
  
  /**
    1 = fast but little detail, .. larger numbers cost more performance, only used for turbulence
  **/
  public var Levels : unreal.Int32;
  
  /**
    How multiple frequencies are getting combined
  **/
  public var bTurbulence : Bool;
  
  /**
    Noise function, affects performance and look
  **/
  public var NoiseFunction : unreal.ENoiseFunction;
  
  /**
    0 = fast, allows to pick a different implementation, can affect performance and look
  **/
  public var Quality : unreal.Int32;
  
  /**
    can also be done with a multiply on the Position
  **/
  public var Scale : unreal.Float32;
  
  /**
    scalar, to clamp the Levels at pixel level, can be computed like this: max(length(ddx(Position)), length(ddy(Position))
  **/
  public var FilterWidth : unreal.FExpressionInput;
  
  /**
    2 to 3 dimensional vector
  **/
  public var Position : unreal.FExpressionInput;
  
}
