/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, its properties/methods are inaccessible
  
  
**/
@:glueCppIncludes("Particles/Beam/ParticleModuleBeamModifier.h")
@:noClass @:uextern extern class UParticleModuleBeamModifier extends unreal.UParticleModuleBeamBase {
  
  /**
    The value to use when modifying the Strength.
  **/
  public var Strength : unreal.FRawDistributionFloat;
  
  /**
    The options associated with the Strength.
  **/
  public var StrengthOptions : unreal.FBeamModifierOptions;
  
  /**
    If true, don't transform the tangent modifier into the tangent basis.
  **/
  public var bAbsoluteTangent : Bool;
  
  /**
    The value to use when modifying the Tangent.
  **/
  public var Tangent : unreal.FRawDistributionVector;
  
  /**
    The options associated with the Tangent.
  **/
  public var TangentOptions : unreal.FBeamModifierOptions;
  
  /**
    The value to use when modifying the position.
  **/
  public var Position : unreal.FRawDistributionVector;
  
  /**
    The options associated with the position.
  **/
  public var PositionOptions : unreal.FBeamModifierOptions;
  
  /**
    Whether this module modifies the Source or the Target.
  **/
  public var ModifierType : unreal.BeamModifierType;
  
}
