/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Particles/Velocity/ParticleModuleVelocityOverLifetime.h")
@:uextern extern class UParticleModuleVelocityOverLifetime extends unreal.UParticleModuleVelocityBase {
  
  /**
    If true, the velocity will be SET to the value from the above dist.
    If false, the velocity will be scaled by the above dist.
  **/
  public var Absolute : Bool;
  
  /**
    The scaling  value applied to the velocity.
    Value is retrieved using the RelativeTime of the particle.
  **/
  public var VelOverLife : unreal.FRawDistributionVector;
  
}
