/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Particles/Attractor/ParticleModuleAttractorBase.h")
@:uextern extern class UParticleModuleAttractorBase extends unreal.UParticleModule {
  
}
