/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;


/**
  WARNING: This type was defined as MinimalAPI on its declaration. Because of that, its properties/methods are inaccessible
  
  
**/
@:glueCppIncludes("Particles/Rotation/ParticleModuleMeshRotation.h")
@:uextern extern class UParticleModuleMeshRotation extends unreal.UParticleModuleRotationBase {
  
  /**
    If true, apply the parents rotation as well.
  **/
  public var bInheritParent : Bool;
  
  /**
    Initial rotation in ROTATIONS PER SECOND (1 = 360 degrees).
    The value is retrieved using the EmitterTime.
  **/
  public var StartRotation : unreal.FRawDistributionVector;
  
}
