/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Engine/PlatformInterfaceWebResponse.h")
@:uextern extern class UPlatformInterfaceWebResponse extends unreal.UObject {
  
  /**
    For non-string results, this is the response
  **/
  public var BinaryResponse : unreal.TArray<unreal.UInt8>;
  
  /**
    For string results, this is the response
  **/
  public var StringResponse : unreal.FString;
  
  /**
    A user-specified tag specified with the request
  **/
  public var Tag : unreal.Int32;
  
  /**
    Result code from the response (200=OK, 404=Not Found, etc)
  **/
  public var ResponseCode : unreal.Int32;
  
  /**
    This holds the original requested URL
  **/
  public var OriginalURL : unreal.FString;
  
}
