/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal;


/**
  Selects a child node based on the value of a boolean parameter
**/
@:glueCppIncludes("Sound/SoundNodeBranch.h")
@:uextern extern class USoundNodeBranch extends unreal.USoundNode {
  
  /**
    The name of the boolean parameter to use to determine which branch we should take
  **/
  public var BoolParameterName : unreal.FName;
  
}
