/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.oculusaudio;

@:umodule("OculusAudio")
@:glueCppIncludes("Private/OculusAudioSettings.h")
@:uextern @:uclass extern class UOculusAudioSettings extends unreal.UObject {
  @:uproperty public var ReflectionCoefFront : unreal.Float32;
  @:uproperty public var ReflectionCoefBack : unreal.Float32;
  @:uproperty public var ReflectionCoefDown : unreal.Float32;
  @:uproperty public var ReflectionCoefUp : unreal.Float32;
  @:uproperty public var ReflectionCoefLeft : unreal.Float32;
  @:uproperty public var ReflectionCoefRight : unreal.Float32;
  @:uproperty public var Depth : unreal.Float32;
  @:uproperty public var Height : unreal.Float32;
  @:uproperty public var Width : unreal.Float32;
  @:uproperty public var LateReverberation : Bool;
  @:uproperty public var EarlyReflections : Bool;
  
}
