/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.androidruntimesettings;

@:umodule("AndroidRuntimeSettings")
@:glueCppIncludes("Classes/AndroidRuntimeSettings.h")
@:uname("EAndroidAudio.Type")
@:uextern @:uenum extern enum EAndroidAudio {
  
  /**
    This option selects the default encoder.
    @DisplayName Default
  **/
  @DisplayName("Default")
  Default;
  
  /**
    Selects Ogg Vorbis encoding.
    @DisplayName Ogg Vorbis
  **/
  @DisplayName("Ogg Vorbis")
  OGG;
  
  /**
    This option selects ADPCM lossless encoding.
    @DisplayName ADPCM
  **/
  @DisplayName("ADPCM")
  ADPCM;
  
}
