/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gameplayabilities;

@:umodule("GameplayAbilities")
@:glueCppIncludes("Abilities/GameplayAbilityTargetActor_GroundTrace.h")
@:uextern @:uclass extern class AGameplayAbilityTargetActor_GroundTrace extends unreal.gameplayabilities.AGameplayAbilityTargetActor_Trace {
  
  /**
    Height for a capsule. Implicitly indicates a capsule is desired if this is greater than zero.
  **/
  @:uproperty public var CollisionHeight : unreal.Float32;
  
  /**
    Radius for a sphere or capsule.
  **/
  @:uproperty public var CollisionRadius : unreal.Float32;
  
}
