/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gameplayabilities;

/**
  Repeat a task a certain number of times at a given interval.
**/
@:umodule("GameplayAbilities")
@:glueCppIncludes("Abilities/Tasks/AbilityTask_Repeat.h")
@:uextern @:uclass extern class UAbilityTask_Repeat extends unreal.gameplayabilities.UAbilityTask {
  @:uproperty public var OnFinished : unreal.gameplayabilities.FRepeatedActionDelegate;
  @:uproperty public var OnPerformAction : unreal.gameplayabilities.FRepeatedActionDelegate;
  
  /**
    Start a task that repeats an action or set of actions.
  **/
  @:ufunction(BlueprintCallable) static public function RepeatAction(OwningAbility : unreal.gameplayabilities.UGameplayAbility, TimeBetweenActions : unreal.Float32, TotalActionCount : unreal.Int32) : unreal.gameplayabilities.UAbilityTask_Repeat;
  
}
