/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.vreditor;

/**
  WARNING: This type was not defined as DLL export on its declaration. Because of that, some of its methods are inaccessible
  
  Represents an interactive floating UI panel in the VR Editor
**/
@:umodule("VREditor")
@:glueCppIncludes("UI/VREditorRadialFloatingUI.h")
@:noClass @:uextern @:uclass extern class AVREditorRadialFloatingUI extends unreal.vreditor.AVREditorBaseActor {
  
  /**
    The central helper widget
  **/
  @:uproperty private var CentralWidgetComponent : unreal.vreditor.UVREditorWidgetComponent;
  
  /**
    The arrow indicator mesh
  **/
  @:uproperty private var ArrowMeshComponent : unreal.UStaticMeshComponent;
  
  /**
    The floating window mesh
  **/
  @:uproperty private var WindowMeshComponent : unreal.UStaticMeshComponent;
  
  /**
    When in a spawned state, this is the widget component to represent the widget
  **/
  @:uproperty private var WidgetComponents : unreal.TArray<unreal.vreditor.UVREditorWidgetComponent>;
  
}
