/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.vectorvm;


/**
  Curve object; encapsulates a curve for the VectorVM
**/
@:umodule("VectorVM")
@:glueCppIncludes("VectorVMDataObject.h")
@:uextern extern class UNiagaraCurveDataObject extends unreal.vectorvm.UNiagaraDataObject {
  public var CurveObj : unreal.UCurveVector;
  
}
