/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.moviescene;

/**
  Enum used to define how to update to a particular time
**/
@:umodule("MovieScene")
@:glueCppIncludes("Public/MovieSceneSequencePlayer.h")
@:uname("EUpdatePositionMethod")
@:class @:uextern @:uenum extern enum EUpdatePositionMethod {
  
  /**
    Update from the current position to a specified position (including triggering events), using the current player status
  **/
  Play;
  
  /**
    Jump to a specified position (without triggering events in between), using the current player status
  **/
  Jump;
  
  /**
    Jump to a specified position, temporarily using EMovieScenePlayerStatus::Scrubbing
  **/
  Scrub;
  
}
