/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.umg;


/**
  Editable text box widget
**/
@:umodule("UMG")
@:glueCppIncludes("Components/EditableText.h")
@:uextern extern class UEditableText extends unreal.umg.UWidget {
  
  /**
    Whether to select all text when pressing enter to commit changes
  **/
  public var SelectAllTextOnCommit : Bool;
  
  /**
    Whether to clear keyboard focus when pressing enter to commit changes
  **/
  public var ClearKeyboardFocusOnCommit : Bool;
  
  /**
    Whether to allow the user to back out of changes when they press the escape key
  **/
  public var RevertTextOnEscape : Bool;
  
  /**
    Whether to select all text when the user clicks to give focus on the widget
  **/
  public var SelectAllTextWhenFocused : Bool;
  
  /**
    Workaround as we lose focus when the auto completion closes.
  **/
  public var IsCaretMovedWhenGainFocus : Bool;
  
  /**
    Minimum width that a text block should be
  **/
  public var MinimumDesiredWidth : unreal.Float32;
  
  /**
    Sets whether this text box is for storing a password
  **/
  public var IsPassword : Bool;
  
  /**
    Sets whether this text box can actually be modified interactively by the user
  **/
  public var IsReadOnly : Bool;
  
  /**
    Text color and opacity (overrides Style)
  **/
  public var ColorAndOpacity_DEPRECATED : unreal.slatecore.FSlateColor;
  
  /**
    Font color and opacity (overrides Style)
  **/
  public var Font_DEPRECATED : unreal.slatecore.FSlateFontInfo;
  
  /**
    Image brush used for the caret (overrides Style)
  **/
  public var CaretImage_DEPRECATED : unreal.USlateBrushAsset;
  
  /**
    Background image for the composing text (overrides Style)
  **/
  public var BackgroundImageComposing_DEPRECATED : unreal.USlateBrushAsset;
  
  /**
    Background image for the selected text (overrides Style)
  **/
  public var BackgroundImageSelected_DEPRECATED : unreal.USlateBrushAsset;
  
  /**
    Text style
  **/
  public var Style_DEPRECATED : unreal.slatecore.USlateWidgetStyleAsset;
  
  /**
    The style
  **/
  public var WidgetStyle : unreal.slatecore.FEditableTextStyle;
  
}
