/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.umg;


/**
  This is the base class for all wrapped Slate controls that are exposed to UObjects.
**/
@:umodule("UMG")
@:glueCppIncludes("Components/Widget.h")
@:uextern extern class UWidget extends unreal.umg.UVisual {
  
  /**
    Common Bindings - If you add any new common binding, you must provide a UPropertyBinder for it.
                      all primitive binding in UMG goes through native binding evaluators to prevent
                      thunking through the VM.
  **/
  public function GetBool__DelegateSignature() : Bool;
  public function GetFloat__DelegateSignature() : unreal.Float32;
  public function GetInt32__DelegateSignature() : unreal.Int32;
  public function GetSlateColor__DelegateSignature() : unreal.slatecore.FSlateColor;
  public function GetLinearColor__DelegateSignature() : unreal.FLinearColor;
  public function GetSlateBrush__DelegateSignature() : unreal.slatecore.FSlateBrush;
  public function GetSlateVisibility__DelegateSignature() : unreal.umg.ESlateVisibility;
  public function GetMouseCursor__DelegateSignature() : unreal.EMouseCursor;
  public function GetCheckBoxState__DelegateSignature() : unreal.slatecore.ECheckBoxState;
  public function GetWidget__DelegateSignature() : unreal.umg.UWidget;
  
  /**
    Events
  **/
  public function GenerateWidgetForString__DelegateSignature(Item : unreal.FString) : unreal.umg.UWidget;
  public function GenerateWidgetForObject__DelegateSignature(Item : unreal.UObject) : unreal.umg.UWidget;
  
  /**
    Events
  **/
  public function OnReply__DelegateSignature() : unreal.umg.FEventReply;
  public function OnPointerEvent__DelegateSignature(MyGeometry : unreal.slatecore.FGeometry, MouseEvent : unreal.Const<unreal.PRef<unreal.slatecore.FPointerEvent>>) : unreal.umg.FEventReply;
  
  /**
    Native property bindings.
  **/
  private var NativeBindings : unreal.TArray<unreal.umg.UPropertyBinding>;
  #if WITH_EDITORONLY_DATA
  
  /**
    Stores a reference to the asset responsible for this widgets construction.
  **/
  public var WidgetGeneratedBy : unreal.UObject;
  
  /**
    Stores the design time flag setting if the widget is expanded inside the designer
  **/
  public var bExpandedInDesigner : Bool;
  
  /**
    Stores the design time flag setting if the widget is hidden inside the designer
  **/
  public var bHiddenInDesigner : Bool;
  #end // WITH_EDITORONLY_DATA
  
  /**
    The navigation object for this widget is optionally created if the user has configured custom
    navigation rules for this widget in the widget designer.  Those rules determine how navigation transitions
    can occur between widgets.
  **/
  public var Navigation : unreal.umg.UWidgetNavigation;
  
  /**
    The render transform pivot controls the location about which transforms are applied.
    This value is a normalized coordinate about which things like rotations will occur.
  **/
  public var RenderTransformPivot : unreal.FVector2D;
  
  /**
    The render transform of the widget allows for arbitrary 2D transforms to be applied to the widget.
  **/
  public var RenderTransform : unreal.umg.FWidgetTransform;
  
  /**
    The cursor to show when the mouse is over the widget
  **/
  public var Cursor : unreal.EMouseCursor;
  public var bOverride_Cursor : Bool;
  
  /**
    The visibility of the widget
  **/
  public var Visibility : unreal.umg.ESlateVisibility;
  
  /**
    The visibility of the widget
  **/
  public var Visiblity_DEPRECATED : unreal.umg.ESlateVisibility;
  
  /**
    Tooltip widget to show when the user hovers over the widget with the mouse
  **/
  public var ToolTipWidget : unreal.umg.UWidget;
  
  /**
    Sets whether this widget can be modified interactively by the user
  **/
  public var bIsEnabled : Bool;
  
  /**
    The parent slot of the UWidget.  Allows us to easily inline edit the layout controlling this widget.
  **/
  public var Slot : unreal.umg.UPanelSlot;
  
  /**
    Flag if the Widget was created from a blueprint
  **/
  public var bCreatedByConstructionScript : Bool;
  
  /**
    Allows controls to be exposed as variables in a blueprint.  Not all controls need to be exposed
    as variables, so this allows only the most useful ones to end up being exposed.
  **/
  public var bIsVariable : Bool;
  @:final public function SetRenderTransform(InTransform : unreal.umg.FWidgetTransform) : Void;
  @:final public function SetRenderScale(Scale : unreal.FVector2D) : Void;
  @:final public function SetRenderShear(Shear : unreal.FVector2D) : Void;
  @:final public function SetRenderAngle(Angle : unreal.Float32) : Void;
  @:final public function SetRenderTranslation(Translation : unreal.FVector2D) : Void;
  @:final public function SetRenderTransformPivot(Pivot : unreal.FVector2D) : Void;
  
  /**
    Gets the current enabled status of the widget
  **/
  @:thisConst @:final public function GetIsEnabled() : Bool;
  
  /**
    Sets the current enabled status of the widget
  **/
  @:final public function SetIsEnabled(bInIsEnabled : Bool) : Void;
  
  /**
    Sets a custom widget as the tooltip of the widget.
  **/
  @:final public function SetToolTip(Widget : unreal.umg.UWidget) : Void;
  
  /**
    Sets the cursor to show over the widget.
  **/
  @:final public function SetCursor(InCursor : unreal.EMouseCursor) : Void;
  
  /**
    Resets the cursor to use on the widget, removing any customization for it.
  **/
  @:final public function ResetCursor() : Void;
  
  /**
    @return true if the widget is Visible, HitTestInvisible or SelfHitTestInvisible.
  **/
  @:thisConst @:final public function IsVisible() : Bool;
  
  /**
    Gets the current visibility of the widget.
  **/
  @:thisConst @:final public function GetVisibility() : unreal.umg.ESlateVisibility;
  
  /**
    Sets the visibility of the widget.
  **/
  @:final public function SetVisibility(InVisibility : unreal.umg.ESlateVisibility) : Void;
  
  /**
    Sets the forced volatility of the widget.
  **/
  @:final public function ForceVolatile(bForce : Bool) : Void;
  
  /**
    @return true if the widget is currently being hovered by a pointer device
  **/
  @:thisConst @:final public function IsHovered() : Bool;
  
  /**
    Checks to see if this widget currently has the keyboard focus
    
    @return  True if this widget has keyboard focus
  **/
  @:thisConst @:final public function HasKeyboardFocus() : Bool;
  
  /**
    Checks to see if this widget is the current mouse captor
    @return  True if this widget has captured the mouse
  **/
  @:thisConst @:final public function HasMouseCapture() : Bool;
  
  /**
    Sets the focus to this widget.
  **/
  @:final public function SetKeyboardFocus() : Void;
  
  /**
    @return true if this widget is focused by a specific user.
  **/
  @:thisConst @:final public function HasUserFocus(PlayerController : unreal.APlayerController) : Bool;
  
  /**
    @return true if this widget is focused by any user.
  **/
  @:thisConst @:final public function HasAnyUserFocus() : Bool;
  
  /**
    @return true if any descendant widget is focused by any user.
  **/
  @:thisConst @:final public function HasFocusedDescendants() : Bool;
  
  /**
    @return true if any descendant widget is focused by a specific user.
  **/
  @:thisConst @:final public function HasUserFocusedDescendants(PlayerController : unreal.APlayerController) : Bool;
  
  /**
    Sets the focus to this widget for a specific user
  **/
  @:final public function SetUserFocus(PlayerController : unreal.APlayerController) : Void;
  
  /**
    Forces a pre-pass.  A pre-pass caches the desired size of the widget hierarchy owned by this widget.
    One pre-pass is already happens for every widget before Tick occurs.  You only need to perform another
    pre-pass if you are adding child widgets this frame and want them to immediately be visible this frame.
  **/
  @:final public function ForceLayoutPrepass() : Void;
  
  /**
    Invalidates the widget from the view of a layout caching widget that may own this widget.
    will force the owning widget to redraw and cache children on the next paint pass.
  **/
  @:final public function InvalidateLayoutAndVolatility() : Void;
  
  /**
    Gets the widgets desired size.
    NOTE: The underlying Slate widget must exist and be valid, also at least one pre-pass must
          have occurred before this value will be of any use.
    
    @return The widget's desired size
  **/
  @:thisConst @:final public function GetDesiredSize() : unreal.FVector2D;
  
  /**
    Gets the parent widget
  **/
  @:thisConst @:final public function GetParent() : unreal.umg.UPanelWidget;
  
  /**
    Removes the widget from its parent widget.  If this widget was added to the player's screen or the viewport
    it will also be removed from those containers.
  **/
  public function RemoveFromParent() : Void;
  
}
