/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.gameplayabilities;


/**
  WARNING: This type is defined as NoExport by UHT. It will be empty because of it
  
  
**/
@:umodule("GameplayAbilities")
@:glueCppIncludes("GameplayEffectTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FGameplayModifierEvaluatedData {
  @:uproperty public var IsValid : Bool;
  
  /**
    Handle of the active gameplay effect that originated us. Will be invalid in many cases
  **/
  @:uproperty public var Handle : unreal.gameplayabilities.FActiveGameplayEffectHandle;
  @:uproperty public var Magnitude : unreal.Float32;
  
  /**
    The numeric operation of this modifier: Override, Add, Multiply, etc
  **/
  @:uproperty public var ModifierOp : unreal.gameplayabilities.EGameplayModOp;
  @:uproperty public var Attribute : unreal.gameplayabilities.FGameplayAttribute;
  
}
