/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.slatecore;


/**
  Settings for applying an outline to a font
**/
@:glueCppIncludes("Framework/Styling/EditableTextBoxWidgetStyle.h")
@:uextern extern class FFontOutlineSettings {
  
  /**
    If checked, the outline will be completely translucent where the filled area will be.  This allows for a separate fill alpha value
    The trade off when enabling this is slightly worse quality for completely opaque fills where the inner outline border meets the fill area
  **/
  public var bSeparateFillAlpha : Bool;
  
  /**
    The color of the outline for any character in this font
  **/
  public var OutlineColor : unreal.FLinearColor;
  
  /**
    Optional material to apply to the outline
  **/
  public var OutlineMaterial : unreal.UObject;
  
  /**
    Size of the outline in slate units (at 1.0 font scale this unit is a pixel)
  **/
  public var OutlineSize : unreal.Int32;
  
}
