/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.slatecore;


/**
  Payload data describing an individual font in a typeface.
**/
@:umodule("SlateCore")
@:glueCppIncludes("Engine/Font.h")
@:uextern extern class FFontData {
  
  /**
    The data associated with the font - this should always be filled in providing the source font filename is valid
  **/
  public var FontData_DEPRECATED : unreal.TArray<unreal.UInt8>;
  
  /**
    The hinting algorithm to use with the font
  **/
  public var Hinting : unreal.slatecore.EFontHinting;
  
  /**
    The data associated with the font
  **/
  public var BulkDataPtr : unreal.slatecore.UFontBulkData;
  
  /**
    The filename of the font to use - this may not always exist on disk, as we may have previously loaded and cached the font data inside an asset
  **/
  public var FontFilename : unreal.FString;
  
}
