/**
  This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
  In order to add more definitions, create or edit a type with the same name/package, but with a `_Extra` suffix
**/
package unreal.slatecore;


/**
  FNavigationEvent describes a navigation action (Left, Right, Up, Down)
  It is passed to event handlers dealing with navigation.
**/
@:umodule("SlateCore")
@:glueCppIncludes("Fonts/FontBulkData.h", "Fonts/FontProviderInterface.h", "Styling/SlateTypes.h", "Styling/SlateWidgetStyleAsset.h", "Styling/SlateWidgetStyleContainerBase.h", "Styling/SlateWidgetStyleContainerInterface.h")
@:uextern extern class FNavigationEvent extends unreal.slatecore.FInputEvent {
  
}
