/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/Sound/SoundAttenuation.h")
@:uname("ESoundSpatializationAlgorithm")
@:uextern @:uenum extern enum ESoundSpatializationAlgorithm {
  
  /**
    Standard panning method for spatialization, built-in to the audio engine.
    @DisplayName Panning
  **/
  @DisplayName("Panning")
  SPATIALIZATION_Default;
  
  /**
    3rd party binaural spatialization (HRTF, Atmos). Requires a spatializaton plugin.
    @DisplayName Binaural
  **/
  @DisplayName("Binaural")
  SPATIALIZATION_HRTF;
  
}
