/**
 * 
 * WARNING! This file was autogenerated by: 
 *  _   _ _   _ __   __ 
 * | | | | | | |\ \ / / 
 * | | | | |_| | \ V /  
 * | | | |  _  | /   \  
 * | |_| | | | |/ /^\ \ 
 *  \___/\_| |_/\/   \/ 
 * 
 * This file was autogenerated by UnrealHxGenerator using UHT definitions.
 * It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
 * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal;

@:glueCppIncludes("Classes/AI/Navigation/NavigationAvoidanceTypes.h")
@:noCopy @:noEquals @:uextern @:ustruct extern class FNavAvoidanceMask {
  @:uproperty public var bGroup31 : Bool;
  @:uproperty public var bGroup30 : Bool;
  @:uproperty public var bGroup29 : Bool;
  @:uproperty public var bGroup28 : Bool;
  @:uproperty public var bGroup27 : Bool;
  @:uproperty public var bGroup26 : Bool;
  @:uproperty public var bGroup25 : Bool;
  @:uproperty public var bGroup24 : Bool;
  @:uproperty public var bGroup23 : Bool;
  @:uproperty public var bGroup22 : Bool;
  @:uproperty public var bGroup21 : Bool;
  @:uproperty public var bGroup20 : Bool;
  @:uproperty public var bGroup19 : Bool;
  @:uproperty public var bGroup18 : Bool;
  @:uproperty public var bGroup17 : Bool;
  @:uproperty public var bGroup16 : Bool;
  @:uproperty public var bGroup15 : Bool;
  @:uproperty public var bGroup14 : Bool;
  @:uproperty public var bGroup13 : Bool;
  @:uproperty public var bGroup12 : Bool;
  @:uproperty public var bGroup11 : Bool;
  @:uproperty public var bGroup10 : Bool;
  @:uproperty public var bGroup9 : Bool;
  @:uproperty public var bGroup8 : Bool;
  @:uproperty public var bGroup7 : Bool;
  @:uproperty public var bGroup6 : Bool;
  @:uproperty public var bGroup5 : Bool;
  @:uproperty public var bGroup4 : Bool;
  @:uproperty public var bGroup3 : Bool;
  @:uproperty public var bGroup2 : Bool;
  @:uproperty public var bGroup1 : Bool;
  @:uproperty public var bGroup0 : Bool;
  
}
