/**
   * 
   * WARNING! This file was autogenerated by: 
   *  _   _ _____     ___   _   _ __   __ 
   * | | | |  ___|   /   | | | | |\ \ / / 
   * | | | | |__    / /| | | |_| | \ V /  
   * | | | |  __|  / /_| | |  _  | /   \  
   * | |_| | |___  \___  | | | | |/ /^\ \ 
   *  \___/\____/      |_/ \_| |_/\/   \/ 
   * 
   * This file was autogenerated by UE4HaxeExternGenerator using UHT definitions. It only includes UPROPERTYs and UFUNCTIONs. Do not modify it!
   * In order to add more definitions, create or edit a type with the same name/package, but with an `_Extra` suffix
**/
package unreal.netcodeunittest;


/**
  Base class for all unit tests
**/
@:glueCppIncludes("UnitTest.h")
@:uextern extern class UUnitTest extends unreal.netcodeunittest.UUnitTestBase {
  
  /**
    Whether or not the success or failure of the current unit test has been verified
  **/
  private var VerificationState : unreal.netcodeunittest.EUnitTestVerification;
  
  /**
    The amount of time it took to execute the unit test the last time it was run
  **/
  public var LastExecutionTime : unreal.Float32;
  
  /**
    The amount of time it takes to reach 'PeakMemoryUsage' (or within 90% of its value)
  **/
  public var TimeToPeakMem : unreal.Float32;
  
  /**
    Stores stats on the highest-ever reported memory usage, for this unit test - for estimating memory usage
  **/
  public var PeakMemoryUsage : unreal.FakeUInt64;
  
}
